### ISSUE TITLE
Best way to upgrade from 1.0.0-alpha to lastest

### ISSUE THREAD

**Issue by qlands** [NaturalHistoryMuseum/ckanext-doi#111]
Hello,

We have been tasked with migrating this plugin's working version (1.0.0-alpha) to the newest version. I guess the best course of action is to perform a step-by-step migration. For example, from 1.0.0-alpha to 2.0.2 and then to 3.x.

We can see that in version 2.0.2, you created a paste command called "update_doi." Is this command intended for migrating DOIs from Schema 3.1 to 4.2?

**Comment by alycejenni** [comment]
That command generates an XML dict based on the new schema, then checks it against the XML on DataCite and updates it if it's different, so yes, it can be used to migrate DOIs between schemas.

At v2.0.2 it will update to schema 4.2, but it doesn't matter what the starting schema is (unless it breaks the `xmltodict` function somehow).

**Comment by qlands** [comment]
Great! Thank you
