### ISSUE TITLE
Enabling DataCite

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [NaturalHistoryMuseum/ckanext-doi#37]
Hi,

I installed the datacite plugin in ckan. Under ckannext is the cloned repro of this datacite plugin. I run _python setup.py develop_ 
Directory structure is ckannext/datacite/setup.py
In the ini-file i wrote my config down:
ckanext.doi.account_name = xxx
ckanext.doi.account_password = pass
ckanext.doi.prefix = 1111
ckanext.doi.publisher = xxx
ckanext.doi.test_mode = True
#ckanext.doi.site_url =  # Defaults to ckan.site_url if not set
#ckanext.doi.site_title = # Optional - site title to use in the citation - eg Natural History Museum Data Portal (data.nhm.ac.uk)

But nothing i can see under the Dataset of ckan, there no DOI.
What i did wrong?

**Comment by jrdh** [comment]
Hi @MichaelHarmsTIB, in your ckan config, have you added `doi` to your plugins list?

**Comment by MichaelHarmsTIB** [comment]
Hi,

 

no I havn’t. I will try. Thx!

 

Regards

 

Michael

 

Von: Josh Humphries [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Juli 2019 10:26
An: NaturalHistoryMuseum/ckanext-doi
Cc: Harms, Michael; Mention
Betreff: Re: [NaturalHistoryMuseum/ckanext-doi] Enabling DataCite (#37)

 

Hi @MichaelHarmsTIB <https://github.com/MichaelHarmsTIB> , in your ckan config, have you added doi to your plugins list?
