### ISSUE TITLE
Shouldn't assume package_update == package_show

### ISSUE THREAD

**Issue by alycejenni** [NaturalHistoryMuseum/ckanext-doi#43]
The outputs of `package_update()` (i.e. `pkg_dict` in `after_update()`) and `package_show()` may not be the same; need to find a new way of checking for changes after updating a package.

https://github.com/NaturalHistoryMuseum/ckanext-doi/blob/dae1385c8bafd1213ef20031658b4f6cc65bbca0/ckanext/doi/plugin.py#L81

**Comment by mdlux** [comment]
Hei, we confirm we have an issue with this. The check was failing, and we needed to disable the comparison:
if cmp(orig_metadata_dict, metadata_dict) != 0:

Any plan about solving this issue?

**Comment by alycejenni** [comment]
You've asked at an excellent time, because I just released [v2.0.2](https://github.com/NaturalHistoryMuseum/ckanext-doi/releases/tag/v2.0.2) which should fix this issue!

**Comment by mdlux** [comment]
Thank you!
