### ISSUE TITLE
CKAN 2.9 compatibility?

### ISSUE THREAD

**Issue by Tegomena** [NaturalHistoryMuseum/ckanext-doi#44]
Dear all,

I tried to install and activate the DOI plugin in CKAN 2.9, but it failed. I executed the "2to3" script on the cloned Git repository, after that, CKAN came up without errors. Unfortunately, creating a dataset was then no more possible, it crashes with a "Internal Server Error" message.

Are there any plans to make the DOI plugin compatible with CKAN 2.9?

**Comment by jrdh** [comment]
Hey @Tegomena, we have just started working on upgrading all of our extensions to v2.9 so yes and hopefully soon! I'll make sure to update this issue with info as we go.

**Comment by Tegomena** [comment]
Thanks a lot, we are looking forward and are appreciating your work! As we are running test environments, we could also test new code.

**Comment by alycejenni** [comment]
(this has now been done!)
