### ISSUE TITLE
Implementation optional fields for Datacite

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [NaturalHistoryMuseum/ckanext-doi#51]
Hello,
is it possible to implement the optional fields for Datacite? :
https://github.com/NaturalHistoryMuseum/ckanext-doi/blob/2f93c03545885ae0795cea78f49aac66295df763/ckanext/doi/lib/metadata.py#L155
Some not implemented for the default schema. If nobody will do it, how could I implement it?
regards,
Michael

**Comment by hauschke** [comment]
Maybe an update to schema 4.4 (including classification code etc.) would be an option, too.

**Comment by alycejenni** [comment]
You can alter the metadata dictionary by chaining the `build_metadata_dict()` method in another extension's (e.g. your theme extension) `plugin.py`.

https://github.com/NaturalHistoryMuseum/ckanext-doi/blob/2f93c03545885ae0795cea78f49aac66295df763/ckanext/doi/lib/metadata.py#L214-L217

For example, here's how we've implemented that in our `ckanext-nhm` extension:

https://github.com/NaturalHistoryMuseum/ckanext-nhm/blob/35e5a2c4b90ea0b788fe9dabea7e61daae2df44c/ckanext/nhm/plugin.py#L363-L397
