### ISSUE TITLE
Cannot install requirements.txt

### ISSUE THREAD

**Issue by frafra** [NaturalHistoryMuseum/ckanext-doi#52]
https://github.com/NaturalHistoryMuseum/ckanext-doi/blob/55a46e6565dc196a5c4d2f3679e0771d04d4ca4a/requirements.txt#L2

```
ERROR: Directory u'.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Removing intermediate container 71b3ea3e98ce
```

CKAN 2.9.4, Python 2 (as many plugins still rely on Python 2).

**Comment by frafra** [comment]
Just need to enter into the directory with `cd`; cannot install `requirements.txt` from a different folder.

**Comment by frafra** [comment]
By the way, wouldn't be better to use `requirements.txt` to pinpoint the versions and `setup.py` to specify compatible versions, without using `.` or other tricks?

**Comment by alycejenni** [comment]
We've got the same structure/setup across all our CKAN extensions, and it works for us (and I believe it's a fairly common pattern). Unless we find a compelling reason to change it, I think it's staying this way for the time being.

**Comment by frafra** [comment]
You are right, it is a common pattern for CKAN, but it is a terrible pattern for Python extensions, since they cannot be installed anymore (without extra steps) and it is not possible to track the dependencies across modules using the various Python tools that exist.
I will try to convince CKAN developers that it is a terrible idea to break with Python standards and handle dependencies like this, but I can understand that third party extension developers have little interest in moving away from suggestions coming from CKAN.
