### ISSUE TITLE
No need to install datacite from git

### ISSUE THREAD

**Issue by frafra** [NaturalHistoryMuseum/ckanext-doi#53]
https://github.com/NaturalHistoryMuseum/ckanext-doi/blob/2f93c03545885ae0795cea78f49aac66295df763/requirements.txt#L8

There have been new releases after that commit: 1.1.0, 1.1.1, 1.1.2.
They also include https://github.com/inveniosoftware/datacite/pull/50.

**Comment by frafra** [comment]
Hi @alycejenni,
is this repository still maintained? There is PR and some issues if anyone has the time to review them (I cited you as you are the last committer to this repository).

**Comment by alycejenni** [comment]
Hi! It is, I just managed to miss these notifications, sorry! Thanks for the PR and for letting us know about the datacite releases - I'll have a look at that now.
