### ISSUE TITLE
Compatibility with CKAN 2.10

### ISSUE THREAD

**Issue by PitPitoune** [NaturalHistoryMuseum/ckanext-doi#80]
**Description**
Doesn't work with ckan 2.10

**First steps**
Modify Plugin.py to adapt the new function's names of IPackageController

Is there other thing to do ?

**Your Setup**
 - CKAN version: 2.10.1
 - Commit/version of this repo: 3.1.8

**Comment by jrdh** [comment]
Hi @PitPitoune, thanks for reporting this. We have scheduled this and will resolve the problem in the next couple of days, hopefully it won't be require a significant change as you suggest!

**Comment by jrdh** [comment]
The changes have been made and merged, will do a release asap.

**Comment by PitPitoune** [comment]
Thanks a lot !

**Comment by jrdh** [comment]
Released: https://github.com/NaturalHistoryMuseum/ckanext-doi/releases/tag/v3.1.9 / https://pypi.org/project/ckanext-doi/
