### ISSUE TITLE
BibTeX link doesn't work correctly

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/ckanext-doi#87]
Looks like it's linking to the test DataCite API which presumably is down to some funky outcome of the logic here: https://github.com/NaturalHistoryMuseum/ckanext-doi/blob/main/ckanext/doi/theme/templates/doi/snippets/package_citation.html#L49?

As an example, the dataset: https://doi.org/10.5519/zi6w507p has a BibTeX link to https://api.test.datacite.org/dois/application/x-bibtex/10.5519/zi6w507p when it should be https://api.datacite.org/dois/application/x-bibtex/10.5519/zi6w507p (note the lack of "test" in the URL's domain).

**Comment by alycejenni** [comment]
This might be another issue with CKAN's `DEBUG`/`debug` config option that we keep running into at the moment

**Comment by jrdh** [comment]
Maybe add a `get_debug_value` to ckantools.
